name: scout

on: [push]

jobs:
 image_scan:
   name: Build and run custom image
   runs-on: ubuntu-22.04

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Docker setup
     uses: docker-practice/actions-setup-docker@v1
     with:
      docker_version: '20.10.7'

   - name: Docker Image build
     run: docker build -f Dockerfile -t myapp:latest .

   - name: Docker Scout Scan
     run: |
      curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
      sh install-scout.sh
      # Pipe for increased security
      echo ${{ secrets.DOCKERPASS }} | docker login -u ${{ secrets.DOCKERNAME }} --password-stdin
      docker scout quickview
      docker scout cves
      
    # added some optional code for extracting the findings
   - name: Upload Artifact
     uses: actions/upload-artifact@v4
     if: always()
     with:
       name: docker-scout-findings
       path: scout-report.sarif




   

   
